"""Validation for the compute_vessel_junctions tool.

Rebuilds the vessel2vessel example problem through the MCP tool
implementation and compares the junction output byte-for-byte against
the golden files in the vessel2vessel repository (tests/golden/,
generated by the original scripts).

Run directly with a Python that has the v2v package installed:

    python tests/test_v2v_junctions.py [path-to-vessel2vessel-checkout]

Defaults to ~/vessel2vessel.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from snap_trace.tools.v2v_tools import compute_vessel_junctions_impl  # noqa: E402


def read_matrix(path, flip):
    rows = [[float(x) for x in line.split('\t')]
            for line in path.read_text().splitlines() if line.strip()]
    # geometry_data files are stored in SNAP orientation (row 1 at the
    # bottom); the tool takes matrices in core_map orientation (row 0 at
    # the top), so Cartesian per-assembly files are flipped.
    return rows[::-1] if flip else rows


def main():
    v2v_repo = Path(sys.argv[1] if len(sys.argv) > 1 else "~/vessel2vessel").expanduser()
    if not v2v_repo.is_dir():
        print("SKIP: vessel2vessel checkout not found at %s" % v2v_repo)
        return 0

    from v2v.config import get_config_params

    # example problem definition from the repository's config files
    pcfg = get_config_params(str(v2v_repo / "config_files" / "partition.config"), 7)
    core_map = [[int(a) for a in line.strip().split(',')] for line in pcfg[3].split('\n')]
    ring_radii = [float(r) for r in pcfg[4].split(',')]
    sector_angles = [float(s) for s in pcfg[5].split(',')]
    offset = float(pcfg[6])

    jcfg = get_config_params(str(v2v_repo / "config_files" / "snapjuns.config"), 10)
    cyl_lower, cyl_upper = [int(x) for x in jcfg[8].split(',')]
    cart_lower, cart_upper = [int(x) for x in jcfg[9].split(',')]

    geo = v2v_repo / "geometry_data"
    result = compute_vessel_junctions_impl(
        core_map=core_map,
        ring_radii=ring_radii,
        sector_angles=sector_angles,
        offset_angle=offset,
        cylindrical_lower_level=cyl_lower,
        cylindrical_upper_level=cyl_upper,
        cartesian_lower_level=cart_lower,
        cartesian_upper_level=cart_upper,
        assembly_flow_area=read_matrix(geo / "areas_cart_lower.dat", flip=True),
        assembly_flow_area_upper=read_matrix(geo / "areas_cart_upper.dat", flip=True),
        dh_cartesian=read_matrix(geo / "dh_z.dat", flip=True),
        dh_cylindrical_lower=read_matrix(geo / "dh_z_cyl_lower.dat", flip=False),
        dh_cylindrical_upper=read_matrix(geo / "dh_z_cyl_upper.dat", flip=False),
    )

    golden = v2v_repo / "tests" / "golden" / "snap_formatting"
    failures = 0
    for key, fname in [("lower_junction_input", "snap_junctions_lower.dat"),
                       ("upper_junction_input", "snap_junctions_upper.dat"),
                       ("summary", "junction_summary.dat")]:
        expected = (golden / fname).read_text()
        if result[key] == expected:
            print("PASS: %s matches golden (%d bytes)" % (fname, len(expected)))
        else:
            print("FAIL: %s differs from golden" % fname)
            failures += 1

    print("junctions per VESSEL junction: %d" % result["num_junctions_per_vessel_junction"])
    print("core area check: %s" % result["core_area_check"])
    if result["warnings"]:
        print("warnings: %r" % result["warnings"])
    if result["core_area_check"] != "OK":
        failures += 1
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
